name: Auto Assign Author # PR の Assignee として PR 作成者を Assign

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    if: github.actor != 'dependabot[bot]'

    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
